"""Shared helpers for official ONNX numerical-engine test assets."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from onnx.backend.test.loader import load_model_tests

OFFICIAL_TEST_KINDS = (
    "node",
    "real",
    "simple",
    "pytorch-converted",
    "pytorch-operator",
)
EXPECTED_RESULTS_PATH = (
    Path(__file__).resolve().parent / "data" / "test_numerical_engine_expected.json"
)
STATUS_PAGE_PATH = (
    Path(__file__).resolve().parent.parent / "docs" / "test-engine-status.md"
)


@dataclass(frozen=True)
class OfficialTestCase:
    """Minimal metadata needed to load one official ONNX test."""

    case_id: str
    kind: str
    name: str
    model_name: str
    model_dir: str | None
    url: str | None


def collect_official_test_cases() -> list[OfficialTestCase]:
    """Return the full official ONNX backend test suite from on-disk data."""
    cases: list[OfficialTestCase] = []
    for kind in OFFICIAL_TEST_KINDS:
        for case in sorted(load_model_tests(kind=kind), key=lambda c: c.name):
            cases.append(
                OfficialTestCase(
                    case_id=f"{kind}::{case.name}",
                    kind=kind,
                    name=case.name,
                    model_name=(
                        Path(case.model_dir).name
                        if case.model_dir is not None
                        else case.model_name
                    ),
                    model_dir=case.model_dir,
                    url=case.url,
                )
            )
    return cases


def load_expected_results(path: Path = EXPECTED_RESULTS_PATH) -> dict[str, Any]:
    """Load the JSON document containing expected comparison results."""
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def render_status_page(document: dict[str, Any]) -> str:
    """Render a markdown status page from the expected-results JSON document."""
    tests = document["tests"]
    histogram: dict[str, int] = {}
    for entry in tests.values():
        result = entry["expected"]["comparison_result"]
        if result != "OK":
            histogram[result] = histogram.get(result, 0) + 1

    lines = [
        "# Numerical Engine Status",
        "",
        "> This file is automatically generated and verified by `pytest tests/test_numerical_engine_status.py`.",
        "",
        f"- Source: `{document['suite']['source']}`",
        f"- ONNX version: `{document['suite']['onnx_version']}`",
        f"- Case count: `{document['suite']['case_count']}`",
        "",
        "## Error Histogram",
        "",
        "| Count | Result |",
        "| ---: | --- |",
    ]

    if histogram:
        for result, count in sorted(
            histogram.items(),
            key=lambda item: (-item[1], item[0]),
        ):
            lines.append(f"| {count} | {_markdown_cell(result)} |")
    else:
        lines.append("| 0 | _No error results_ |")

    lines += [
        "",
        "## Test Cases",
        "",
        "| Case ID | Result |",
        "| --- | --- |",
    ]

    for case_id, entry in sorted(tests.items()):
        comparison_result = _markdown_cell(entry["expected"]["comparison_result"])
        lines.append(f"| {_markdown_cell(case_id)} | {comparison_result} |")

    return "\n".join(lines) + "\n"


def _markdown_cell(value: Any) -> str:
    text = str(value)
    return text.replace("\\", "\\\\").replace("|", "\\|").replace("\n", "<br>")
